### ISSUE TITLE
Side Effects Shouldn't Activate Cat

### ISSUE THREAD

**Issue by BardBlue** [Lknechtli/BetterCombatEvolved#14]
I thought I saw somewhere that this mod, or maybe another mod, made Side Effects not activate cat. I'm still getting cat from Side Effects, so if that was something this mod used to fix, that'd be nice again. Cat is really annoying outdoors when you don't need it. Or at least, if there was a way to deactivate cat without using white honey, because zero toxicity cat can be useful very occasionally.

**Comment by Lknechtli** [comment]
weird. thought he fixed that.
