### ISSUE TITLE
Put ESGO on git

### ISSUE THREAD

**Issue by TriangleAuthority** [Lknechtli/BetterCombatEvolved#28]
https://github.com/TriangleAuthority/TESGO

nice if you want to see the diffs from vanilla all in one place

**Comment by Lknechtli** [comment]
Not sure why this is an issue.
Did you ask for his permission first? 
Once something's on github public, the user agreement says anyone can fork it, but he hasn't put it up.  His changes are technically under default copyright, so he's the only one allowed to publish it unless he explicitly gives permission.

**Comment by Lknechtli** [comment]
asked him, he doesn't mind as long as you don't claim it as your own.

**Comment by TriangleAuthority** [comment]
not an 'issue', just thought I'd link it :O
