### ISSUE TITLE
Devourer damage too high

### ISSUE THREAD

**Issue by Lknechtli** [Lknechtli/BetterCombatEvolved#3]
JmX1977:

one problematic thing -Devouers explosion is way too damaging. it can easily take whole health bar down, which if you combine with the ability that increases the insta-kill with adrenaline points, you end up killing the Devouer just to get killed by the explosion.. and you cant do anything to prevent it, except trying to fight them at range.

**Comment by Lknechtli** [comment]
Note - you can just unequip the skill during the battle.

**Comment by BardBlue** [comment]
I think their damage is a bit excessive too, especially for how fast it triggers (unlike rotfiends, which is choreographed). It can one-shot you, it seems. Just annoying, not challenging. Cut the damage in half, I say. Still enough to punish you, but not to kill you from practically full health as it seems to now.

**Comment by Lknechtli** [comment]
We're redoing the way that we handle monster difficulty now anyways, to make it more compatible with ESGO
