### ISSUE TITLE
A fix for toxicity, but...

### ISSUE THREAD

**Issue by Chickenudoom** [Lknechtli/BetterCombatEvolved#8]
Changing fast metabolism to anything under -1 makes the tooltip appear as "0", although it works really well. If we can find a way to force the tooltip to show the correct value (was thinking like 0.1 per rank) then that'd be awesome!

Another route we could take is changing max toxicity to around 500, and boost potion/decoction toxicity values accordingly. This method seems a little hacky and would require the user to drink a clearing potion, but it would give us an immense amount of control over toxicity degeneration.

Thoughts?

**Comment by BardBlue** [comment]
Changing max toxicity to 500 sounds dangerous. Have to change that toxicity skill that gives you max toxicity for alchemy formulae known, all the potions, lots of numbers could be tweaked in the wrong way. And I think a lot of people would find it off-putting, having to acclimate to all the new numbers. Then again, you've already changed potions a lot.

Probably so long as you explain in the mod description that the tooltip doesn't display correctly, it's okay, at least for now. Better a buggy display than a buggy (and super OP) effect.
